title: Adventures in learning!
author: lightningholt
email: calebjamesholt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning how to use Jekyll and GitHub Pages via GitHub learning so that I can make respectable website for myself!
  
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  lightningholt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
